In [6]:
# len(list)
list_len = [1,2,3,4,5,6,1,2,3]
length = len(list_len)
print(length)

9


In [5]:
#list.append(item) 
list_append = ["a", "b", "c"]
list_append.append("d")
print(list_append)

['a', 'b', 'c', 'd']


In [9]:
# list.insert(index,item)
list_insert = ["baluka", "lebe", "nodi"]
list_insert.insert(0,"nona")
print(list_insert)

['nona', 'baluka', 'lebe', 'nodi']


In [10]:
#list.remove(item)
list_remove = [1,2,3,4,5,6,1,2,3]
list_remove.remove(6)
print(list_remove)

[1, 2, 3, 4, 5, 1, 2, 3]


In [13]:
#list.pop(index)
list_pop = ["a", "b", "c"]
list_pop.pop(2)
print(list_pop)

['a', 'b']


In [15]:
#list.sort()
list_sort = [1,2,3,4,5,6,1,2,3]
list_sort.sort()
print(list_sort)

[1, 1, 2, 2, 3, 3, 4, 5, 6]


In [16]:
#list.reverse()
list_rev = [1,2,3,4,5,6,1,2,3]
list_rev.reverse()
print(list_rev)

[3, 2, 1, 6, 5, 4, 3, 2, 1]


In [21]:
#len(tuple)
my_tuple = (1,2,3,4,54)
length = len(my_tuple)
print(length)

5


In [26]:
#tuple.index()
my_tuple = ("a", "b", "c")
index = my_tuple.index("a")
print(index)

0


In [32]:
#tuple.count(item)
my_tuple = ("baluka", "lebe", "nodi")
count = my_tuple.count("  ")
print(count)

0


In [30]:
#Dictionaries
#len_dictionaries
my_dict = {"Car":"Chevy", "Color":"White","model":"V10 452"}
result = len(my_dict)
print(result)

3


In [38]:
# dictionary.keys()
my_dict = {"Car":"Chevy", "Color":"White","model":"V10 452"}
key_list = my_dict.keys()
print(key_list)

dict_keys(['Car', 'Color', 'model'])


In [37]:
#dictionary.values()
my_dict = {"Car":"Chevy", "Color":"White","model":"V10 452"}
key_list = my_dict.values()
print(key_list)

dict_values(['Chevy', 'White', 'V10 452'])


In [36]:
# dictionary.item()
my_dict = {"Car":"Chevy", "Color":"White","model":"V10 452"}
key_list = my_dict.items()
print(key_list)

dict_items([('Car', 'Chevy'), ('Color', 'White'), ('model', 'V10 452')])


In [40]:
#dictionay.get(item)
my_dict = {"Car":"Chevy", "Color":"White","model":"V10 452"}
key_list = my_dict.get("car")
print(key_list)

None


In [41]:
#if-elif-else function
num = 24
if (num>0):
    print("positive")
elif (num<0):
    print("negative")
else:
    print("Zero")

positive


In [48]:
#check if a perosn is eligible for vote or not
person = 90
if(person>18):
    print("YES, you are eligible for vote")
elif(person<18):
    print("NO,you are not eligible for vote")
else:
    (person == 18)
    print("You need one more year for eligible for vote")

YES, you are eligible for vote


In [51]:
#while loop
#print number from 1 to 5
num = 1
while num <= 5:
    print(num)
    num +=1

1
2
3
4
5


In [1]:
#calculate the factorial of a number using while loop
n = 5
factorial = 1
while n>0:
    factorial *= n
    n -= 1
print("Factorial:", factorial)

Factorial: 120


In [2]:
#for loop
#iterate over a list of color
color = ["red","blue","green"]

for color in color:
    print(color)

red
blue
green


In [4]:
#calculate the sum of number from 1 to 6
sum_result = 0

for i in range(1,7):
    sum_result += i
print(sum_result)

21


In [6]:
#break statement 
#find the first even number in a list

number = [1,11,7,13,3,4,6,2,10]
for num in number:
    if num % 2 == 0:
        print("First even number found:", num)
        break

First even number found: 4


In [26]:
# search element in a list
target_element = 23
data = [21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
for element in data:
    if element == target_element:
        print("targeted element is found")
        break
else:
    print("target element is not found")
    

targeted element is found


In [7]:
#continue statement
#print odd number from 1 to 5
for i in range(1,6):
    if i%2 == 0:
        continue
    print(i)

1
3
5


In [8]:
#skip negetive numbers
numbers = [2,4,1,-4,0,-5,-9]
for num in numbers:
    if num<0:
        continue
    print("positive numbers", num)

positive numbers 2
positive numbers 4
positive numbers 1
positive numbers 0


In [12]:
#pass statement
#check if a number is even do nothing otherwise
num = 14
if num%2 == 0:
    print("The number is even")
else:
    pass

The number is even


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


In [3]:
import numpy as np


In [ ]:
#having a temperature data for 5 cities(Bangalore, Delhi, Chennai, Kolkata, Mumbai)for the last 5 days

In [23]:
#temperature data
temp_data = np.array([
    [32,32,33,34,35], #Bangalore
    [33,34,34,35,36], #Chennai
    [34,35,36,36,37], #Delhi
    [31,32,32,33,34], #Kolkata
    [33,34,34,35,36]  #Mumbai
    
])

#1.Calculate daily average temperature for each city
daily_avg_temp = np.mean(temp_data, axis = 1) #axis = 1 means count the element fron left to right or horizontally
print("Daily avg temperature of cities in India is :",daily_avg_temp)


Daily avg temperature of cities in India is : [33.2 34.4 35.6 32.4 34.4]


In [24]:
#2. Find the highest average temperature
avg_temp = np.mean(temp_data, axis = 1)
city_highest_temp = np.argmax(avg_temp)
cities = ["Bangalore", "Delhi", "Chennai", "Kolkata", "Mumbai"]
print("City with highest average temparature is:", cities[city_highest_temp])

City with highest average temparature is: Chennai


In [25]:
#3. Calculate the temperature anomalies for each city
temp_anomalies = temp_data-daily_avg_temp[:,np.newaxis]
print(temp_anomalies)

[[-1.2 -1.2 -0.2  0.8  1.8]
 [-1.4 -0.4 -0.4  0.6  1.6]
 [-1.6 -0.6  0.4  0.4  1.4]
 [-1.4 -0.4 -0.4  0.6  1.6]
 [-1.4 -0.4 -0.4  0.6  1.6]]


In [26]:
#problem no.1 - Given a 2D NumPy array 'arr', extract all the even number from the array using advanced indexing.
def extract_even_number(arr):
    return arr[arr%2 == 0]
#Test this function
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
even_numbers = extract_even_number(arr)
print("The even numbers are:", even_numbers)

The even numbers are: [2 4 6 8]


In [27]:
#Problem no.2 - Given a 1D NumPy array arr, add 10 to each element and return the result using broadcasting.
def add_ten(arr):
    return arr+10
#Test this function
arr = np.array([1,2,3,4,5,6,7,8,9])
add_numbers = add_ten(arr)
print("The 10 added numbers are:", add_numbers)

The 10 added numbers are: [11 12 13 14 15 16 17 18 19]


In [34]:
#problem no.3 - Write a python function that takes two 1D NumPy array's (arr1 and arr2) and compute their element-wise multiplication using vectorization
def muliplication(arr1,arr2):
    return arr1*arr2
#Test this function
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result = muliplication(arr1,arr2)
print("The multiplication is :",result)

The multiplication is : [ 5 12 21 32]


In [38]:
#Problem 5 - Given a 2D NumPy array data, write a python function that return the sum of each row as 1D array.
def row_sum(data):
    return np.sum(data,axis = 1)
    
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_sum = row_sum(data)
print(row_sum)

[ 6 15 24]


In [41]:
#Problem 6 - Given a 1D NumPy array arr, replace all negetive value with zeros
def replace(arr):
    arr[arr<0] = 0
    return arr
arr = np.array([1,-2,3,-4,-5])
result = replace(arr)
print(result)

[1 0 3 0 0]
